cashmusic/platform

framework/classes/plants/SystemPlant.php
tests/php/011_SystemPlantTests.php

Now a username held by a deleted account can be reclaimed. It'll stay associated with the account until an active user changes their name. At which point the deleted account is given a blank username and the name is given to the active account.

changed account renaming

---

framework/classes/plants/CommercePlant.php
interfaces/admin/components/pages/controllers/search.php
interfaces/admin/components/pages/views/search_results.mustache
tools/devtools
tools/tests/php/all.php

Also devtools enhancements. (Run test suite without Seed tests)

order search

---

framework/elements/emailcollection/app.json
interfaces/admin/components/pages/views/calendar_venues.mustache
interfaces/admin/components/pages/views/commerce.mustache
interfaces/admin/components/text/en/pages/calendar_venues.json

Tiny fixes like commas, typos, and inappropriate capitalisation.

Tracytime - Minor typo fixes

---

.gitignore
interfaces/admin/admin_template.ini.php
interfaces/admin/components/pages/controllers/login.php
interfaces/admin/constants.php

- added support for an admin.ini.php file to override constants (gitignored, so can be deploy-specific)
- added filters on signup email addresses, allowing us to limit signups

Override admin constants

---

interfaces/admin/components/pages/controllers/mainpage.php

paying more attention to array/false status

---

framework/lib/S3.php

triggered by a warning from Amazon that we should be forcing TLS

updating to newest version, pushing in our changes

---

framework/elements/emailcollection/templates/mustverify.mustache

- fixed custom verification message

Fixed custom verification message fixes #666

---

interfaces/admin/components/pages/views/assets_details.mustache

Fixed "save changes" button bug

---

framework/elements/Store.php
framework/elements/store/templates/cart.mustache

Fixes, for the empty cart state. Bet you couldn't guess that from the branch title tho.

Emptycartfix

---

framework/elements/Store.php

fixed a minor php warning

---

framework/classes/plants/CommercePlant.php

This should fix the BK issues.

Monkeyfuck this method to handle any and all variants, including those with spaces

---

framework/classes/plants/CommercePlant.php
framework/elements/Store.php
framework/elements/store/app.json
framework/elements/store/templates/cart.mustache
framework/elements/store/templates/success.mustache
interfaces/admin/assets/css/embed-default.css

Seems like people were missing the shipping dropdown, so instead of auto-selecting region1, we've added a "Please select region" option and we show shipping as TBD. If someone begins checkout on a physical order without selecting a region we swap the checkout button for two new checkout buttons, one for each region. This forces a conscious choice of regions and reduces "accidents."

force the shipping region choice

---

framework/classes/core/CASHDBA.php
framework/classes/plants/CommercePlant.php
framework/classes/seeds/MandrillSeed.php
framework/classes/seeds/PaypalSeed.php
interfaces/admin/components/pages/controllers/commerce.php
interfaces/admin/components/pages/controllers/commerce_items_edit.php
interfaces/admin/components/pages/controllers/commerce_items_send.php
interfaces/admin/components/pages/controllers/commerce_orders_resend.php
interfaces/admin/components/pages/controllers/commerce_orders_view.php
interfaces/admin/components/pages/controllers/people_lists_export.php
interfaces/admin/components/pages/views/commerce.mustache
interfaces/admin/components/pages/views/commerce_items_edit.mustache
interfaces/admin/components/pages/views/commerce_items_send.mustache
interfaces/admin/components/pages/views/commerce_orders_details.mustache
interfaces/admin/components/pages/views/commerce_orders_resend.mustache
interfaces/admin/components/text/en/pages/commerce_items_edit.json
interfaces/admin/components/text/en/pages/commerce_items_send.json
interfaces/admin/components/text/en/pages/commerce_orders_resend.json
interfaces/admin/components/text/en/pages/commerce_orders_view.json
interfaces/public/download/index.php

there are a few updates ganged in here, but the big ones:
1. find all orders by item sold
2. email all buyers of a specific item (with direct download link)

Commerce changes

---

framework/classes/core/CASHData.php
interfaces/index.php

Removing the fixed homepage in favor of caching a remote site to display locally. Will make this conditional later to allow a dev homepage or external site conditionally. But right now it's YOLO O'clock.

now caching a remote homepage for display/deploy to main cash site

---

README.md

Added logo to the README

---

framework/classes/plants/CommercePlant.php
framework/classes/seeds/StripeSeed.php
interfaces/admin/components/pages/controllers/commerce_orders_view.php
interfaces/admin/components/pages/views/commerce_orders_details.mustache

changed a few keys, added a switch in case there is no shipping coming from stripe, so names aren't blank

stripe tweak to parseTransactionData

---

framework/classes/plants/CommercePlant.php

successful array merge into data field, verified that both the $shipping_info and $geo JSON data are present.
the key for geo in data is... "geo"

$geo var gets added to data field JSON on initiateCheckout

---

interfaces/public/request/request.php

headers everywhere, man

---

interfaces/admin/classes/AdminHelper.php

`$input_data['type'] != 'scalar'` is repeated

Duplicate conditional expression in AdminHelper.php

---

framework/elements/fulfillment/templates/success.mustache
interfaces/admin/assets/css/embed-default.css

fulfillment success state

---

framework/classes/core/CASHDBA.php
framework/elements/TourDates.php

should fix calendar element issues.

calendar results

---

framework/classes/plants/CommercePlant.php
framework/classes/plants/SystemPlant.php
framework/elements/Subscription.php
framework/elements/subscription/templates/default.mustache
framework/elements/subscription/templates/finalize.mustache
framework/elements/subscription/templates/settings.mustache
framework/elements/subscription/templates/verify_success.mustache
interfaces/admin/components/pages/views/elements_details.mustache

Subscriptions

---

framework/classes/plants/CommercePlant.php
framework/elements/subscription/templates/default.mustache

show more user friendly errors on subscriptions
HTTP error code style

verbose errors on subscriptions

---

framework/classes/core/CASHDBA.php
framework/classes/plants/CommercePlant.php
interfaces/admin/components/pages/controllers/commerce_subscriptions_detail.php
interfaces/admin/components/pages/views/commerce_subscriptions_detail.mustache

give some general stats on active subscribers + current active subscription levels

Subscriptions stats

---

interfaces/admin/assets/css/embed-default.css

further updates

---

interfaces/public/index.php

This should give a neater endpoint for downloads. Namely:
{{www_url}}?cash_request_type=asset&cash_action=claim...

nicer public index

---

framework/classes/core/CASHData.php
framework/classes/plants/ElementPlant.php
framework/elements/subscription/app.json
interfaces/admin/classes/AdminHelper.php

merge metadata feed into master

Subscription metadata feed

---

framework/classes/core/CASHRequest.php
framework/classes/core/CASHSystem.php
framework/classes/core/PlantBase.php
interfaces/admin/AdminHelper.php
interfaces/admin/components/pages/controllers/mainpage.php

changed the way routing tables are read to streaming methods

fixed some session issues that probably didn't need to actually be fixed

---

framework/classes/plants/Commerce/routing.json
framework/classes/plants/People/routing.json

added api public and api_key security to routing.json files for all plants

---

framework/elements/digitalpurchase/app.json
framework/elements/downloadcodes/app.json
framework/elements/emailcollection/app.json
framework/elements/fulfillment/app.json
framework/elements/membersarea/app.json
framework/elements/securedownload/app.json
framework/elements/singlepurchase/app.json
framework/elements/socialfeeds/app.json
framework/elements/staticcontent/app.json
framework/elements/store/app.json
framework/elements/subscription/app.json
framework/elements/tourdates/app.json

Hello!
This is the "framework/elements" folder translations for Spanish. I double-checked them sothey should be ready to be merged.

"framework/elements" folder translations for Spanish.

---

interfaces/admin/ui/default/template.mustache

Fixes #954. This pull request is work in progress; it hasn't been tested because I'm not sure how to test it. It is, however, pretty straighforward and a one line change in code. So if anyone can test it and comment on whether it worked, that would be much appreciated.

Changed FAQs to How Tos in template.mustache

---

interfaces/admin/components/text/en/help/buildastore.md
interfaces/admin/components/text/en/help/downloadcodes.md
interfaces/admin/components/text/en/help/emailcollection.md
interfaces/admin/components/text/en/help/mailchimp.md
interfaces/admin/components/text/en/help/paiddownload.md
interfaces/admin/components/text/en/help/physicalrelease.md
interfaces/admin/components/text/en/help/publishingcampaign.md
interfaces/admin/components/text/en/help/s3.md

Clarification to articles in the “FAQ’s” section.

Help text updates

---

interfaces/admin/components/text/en/help/addanelement.md

file :
platform/interfaces/admin/components/text/en/help/addanelement.md

translation to indonesia / addanelement.md

---

interfaces/admin/components/text/en/help/addarelease.md

file :
platform/interfaces/admin/components/text/en/help/addarelease.md

translation to indonesia / addarelease.md

---

interfaces/admin/components/text/en/help/buildastore.md

file :
platform/interfaces/admin/components/text/en/help/buildastore.md

translation to indonesia / buildastore.md

---

interfaces/docs/writing/api.md

File location: interfaces/docs/writing/api.md

Tagalog Translation for api.md

---

interfaces/docs/writing/connections.md

File location: interfaces/docs/writing/connections.md

Tagalog Translation for connections.md

---

interfaces/docs/writing/elements_structure.md

File Location: interfaces/docs/writing/elements_structure.md

Tagalog Translation for elements_structure.md

---

interfaces/admin/components/text/en/help/s3.md

file :
platform/interfaces/admin/components/text/en/help/s3.md

Translation to indonesia / s3.md

---

interfaces/admin/components/text/en/help/paiddownload.md

file :
platform/interfaces/admin/components/text/en/help/paiddownload.md

Translation to indonesia / paiddownload.md

---

interfaces/admin/components/text/en/help/emailcollection.md

file :
platform/interfaces/admin/components/text/en/help/emailcollection.md

 Translation to indonesia / emailcollection.md

---

interfaces/admin/components/text/en/help/downloadcodes.md

file :
platform/interfaces/admin/components/text/en/help/downloadcodes.md

Translation to indonesia / downloadcodes.md

---

interfaces/admin/components/text/en/help/commercesettings.md

file :
platform/interfaces/admin/components/text/en/help/commercesettings.md

Translation to indonesia / commercesettings.md

---

framework/classes/core/CASHConnection.php
framework/classes/core/CASHDaemon.php
framework/classes/core/CASHData.php

hi there, 
I translated 3 classes into Chinese Simplified, pls help to review and confirm the pull request. Should there be any questions, pls feel free to let me know. 
Thanks and best
Susan

Update translation of Chinese Simplified

---

interfaces/docs/writing/api_restfulapi.md

File Location: interfaces/docs/writing/api_restfulapi.md

Tagalog Translation for api_restfulapi.md

---

interfaces/docs/writing/api_verboseapi.md

File Location: interfaces/docs/writing/api_verboseapi.md

Tagalog Translation for api_verboseapi.md

---

interfaces/docs/README.md

File Location: interfaces/docs/README.md

Tagalog Translation for README.md

---

interfaces/docs/writing/phpcore.md

File Location: interfaces/docs/writing/phpcore.md

Tagalog Translation for phpcore.md

---

interfaces/docs/writing/introduction_setup.md

File Location: interfaces/docs/writing/introduction_setup.md

Tagalog Translation for introduction_setup.md

---

interfaces/docs/writing/introduction_codestandards.md

File location: interfaces/docs/writing/introduction_codestandards.md

Tagalog Translation for introduction_codestandards.md

---

interfaces/docs/writing/introduction.md

File Location: interfaces/docs/writing/introduction.md

Tagalog Translation for introduction.md

---

framework/classes/core/CASHConnection.php
framework/classes/core/CASHDaemon.php
framework/classes/core/CASHData.php
framework/elements/DigitalPurchase/app.json
framework/elements/DownloadCodes/app.json
framework/elements/EmailCollection/app.json
framework/elements/Fulfillment/app.json
framework/elements/MembersArea/app.json

Hi There, 
I translated some app.json file under framework/elements into Chinese Simplified, pls help to review and approve. Thanks 
Best
Susan

Cashmusicplatform translation cn

---

interfaces/admin/components/text/en/help/addanelement.md
interfaces/admin/components/text/en/help/addarelease.md
interfaces/admin/components/text/en/help/buildastore.md
interfaces/admin/components/text/en/help/commercesettings.md
interfaces/admin/components/text/en/help/downloadcodes.md

Hello,
I translated this project help files from EN to TUR.
I will continue to translate.
Could you please check it and approve?
Thanks in advance.

Turkish Translation

---

interfaces/admin/components/text/en/help/addanelement.md

File Location: interfaces/admin/components/text/en/help/addanelement.md

Tagalog Translation for addanelement.md

---

interfaces/docs/writing/adminapp.md
interfaces/docs/writing/introduction.md

Please help merge my Vietnamese Translation. File Location: platform/interfaces/docs/writing/

Vietnamese Translation for adminapp.md

---

interfaces/docs/writing/introduction.md

Please help me update Vietnamese Translation for introduction.md. File Location:  platform/interfaces/docs/writing/

Vietnamese Translation for introduction.md

---

interfaces/admin/components/text/en/help/addarelease.md

File Location: interfaces/admin/components/text/en/help/addarelease.md

Tagalog Translation for addarelease.md

---

interfaces/admin/components/text/en/help/buildastore.md

File Location: interfaces/admin/components/text/en/help/buildastore.md

Tagalog Translation for buildastore.md

---

interfaces/admin/components/text/en/help/commercesettings.md

File Location: interfaces/admin/components/text/en/help/commercesettings.md

Tagalog Translation for commercesettings.md

---

interfaces/admin/components/text/en/help/downloadcodes.md

File Location: interfaces/admin/components/text/en/help/downloadcodes.md

Tagalog Translation for downloadcodes.md

---

interfaces/admin/components/text/en/help/terms.md

file :
platform/interfaces/admin/components/text/en/help/

translation to indonesia | terms.md

---

interfaces/admin/components/text/en/help/mailchimp.md

file : 
platform/interfaces/admin/components/text/en/help/

Translation to indonesia | mailchimp.md

---

interfaces/admin/components/text/en/help/gettingstarted.md

file :
platform/interfaces/admin/components/text/en/help/

translationn to indonesia | gettingstarted.md

---

interfaces/admin/components/text/en/help/migratedb.md

file :
platform/interfaces/admin/components/text/en/help/migratedb.md

translation to indonesia | migratedb.md

---

interfaces/admin/components/text/en/help/physicalrelease.md

file :
platform/interfaces/admin/components/text/en/help/physicalrelease.md

Translation to indonesia | physicalrelease.md

---

interfaces/admin/components/text/en/help/paypal.md

platform/interfaces/admin/components/text/en/help/paypal.md

Translation to indonesia | paypal.md

---

framework/elements/SecureDownload/app.json

Cebuano Translation (ceb) for framework/elements/SecureDownload/app.json

Update app.json (Cebuano Translation)

---

interfaces/admin/components/interface/en/interaction.json
interfaces/admin/components/interface/en/menu.json
interfaces/admin/components/text/en/help/addanelement.md
interfaces/admin/components/text/en/help/addarelease.md
interfaces/admin/components/text/en/help/buildastore.md
interfaces/admin/components/text/en/help/commercesettings.md

interaction.json; menu.json; addanelement.md; addarelease.md; buildastore.md; commercesettings.md.

pt_BR translation 6 files

---

interfaces/admin/components/text/en/help/addanelement.md

Hi translate this file addanelement.md, to European Portuguese. Greetings!

pt_PT translation file addanelement.md

---

interfaces/admin/components/text/en/help/paypal.md

Translation to Portuguese of file: platform/interfaces/admin/components/text/en/help/paypal.md

pt_PT translation file: paypal.md

---

interfaces/admin/components/text/en/help/paiddownload.md

Translation to Portuguese of file: platform/interfaces/admin/components/text/en/help/paiddownload.md

pt_PT translation file: paiddownload.md

---

interfaces/admin/components/text/en/help/migratedb.md

Translation to Portuguese of file: platform/interfaces/admin/components/text/en/help/migratedb.md

pt_PT translation file: migratedb.md

---

interfaces/admin/components/text/en/help/mailchimp.md

Translation to Portuguese of file: platform/interfaces/admin/components/text/en/help/mailchimp.md

pt_PT translation file: mailchimp.md

---

interfaces/admin/components/text/en/help/gettingstarted.md

Translation to Portuguese of file: platform/interfaces/admin/components/text/en/help/gettingstarted.md

pt_PT translation file: gettingstarted.md

---

interfaces/admin/components/text/en/help/commercesettings.md

Translation to Portuguese of file: platform/interfaces/admin/components/text/en/help/commercesettings.md

pt_PT translation file: commercesettings.md

---

interfaces/admin/components/text/en/help/buildastore.md

Translation to Portuguese of file: platform/interfaces/admin/components/text/en/help/buildastore.md

pt_PT translation file: buildastore.md

---

interfaces/admin/components/text/en/help/addarelease.md

Translation to Portuguese of file: platform/interfaces/admin/components/text/en/help/addarelease.md

pt_PT translation file menu.json

---

interfaces/admin/components/interface/en/interaction.json

Translation to Portuguese  of  file  platform/interfaces/admin/components/interface/en/ 
interaction.json

pt_PT translation  file interaction.json

---

interfaces/admin/components/interface/en/interaction.json
interfaces/admin/components/interface/en/menu.json
interfaces/admin/components/text/en/help/addanelement.md
interfaces/admin/components/text/en/help/addarelease.md
interfaces/admin/components/text/en/help/buildastore.md
interfaces/admin/components/text/en/help/commercesettings.md
interfaces/admin/components/text/en/help/downloadcodes.md
interfaces/admin/components/text/en/help/emailcollection.md
interfaces/admin/components/text/en/help/gettingstarted.md
interfaces/admin/components/text/en/help/mailchimp.md
interfaces/admin/components/text/en/help/migratedb.md
interfaces/admin/components/text/en/help/paiddownload.md
interfaces/admin/components/text/en/help/paypal.md
interfaces/admin/components/text/en/help/physicalrelease.md
interfaces/admin/components/text/en/help/terms.md

downloadcodes.md; emailcollection.md; physicalrelease.md; terms.md.

pt_BR translation of more 4 files

---

interfaces/admin/components/text/en/help/publishingcampaign.md

Full Translation of publishingcampaign.md, to Portuguese PTPT.
It´s ready to be merged.

publishingcampaign.md portuguese ptpt translation

---

interfaces/admin/components/text/en/help/physicalrelease.md

Full Translation of physicalrelease.md, to Portuguese PTPT.
It´s ready to be merged.

physicalrelease.md portuguese ptpt translation

---

interfaces/admin/components/text/en/help/emailcollection.md

Full Translation of emailcollection.md, to Portuguese PTPT.
It´s ready to be merged.

emailcollection.md portuguese ptpt translation

---

interfaces/admin/components/text/en/help/downloadcodes.md

Full Translation of downloadcodes.md, to Portuguese PTPT.
It´s ready to be merged.

downloadcodes.md portuguese ptpt translation
